image: node:12

before_script:
  - echo "*** Starting Procedure ***"

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - npm run test
  

build:
  stage: build
  before_script:
    - echo $CUSTOMCONNSTR_MONGODB_URL
  script:
    - npm run build
    - npm install --only=prod


Deploy_production:
  stage: deploy
  image: ruby:latest
  before_script:
    - export CUSTOMCONNSTR_MONGODB_URL=$CUSTOMCONNSTR_MONGODB_URL
  script:
    - echo "====== Deploy to production server ======"
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ioannis-product-api --api-key=$CUSTOMCONNSTR_HEROKU_API_KEY
  only:
    - master
